---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: CFDrello-WEB
  namespace: trainee
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: CFDrello-WEB
    spec:
      containers:
      - name: CFDrello-WEB
        image: asia.gcr.io/socialenable4/trainee/CFDrello-WEB:TO_BE_REPLACE_TAG
        ports:
        - name: CFDrello-WEB
          containerPort: 3000