kind: Service
apiVersion: v1
metadata:
  name: cfdrelloweb
  namespace: trainee
spec:
  selector:
    app: cfdrelloweb
  type: NodePort
  ports:
  - name: cfdrelloweb
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30356
