kind: Service
apiVersion: v1
metadata:
  name: cfdrelloweb
  namespace: trainee
spec:
  ports:
  - port: 4200
    protocol: TCP
    targetPort: 4200
    nodePort: 30356
  type: NodePort
  selector:
    app: trainee