kind: Service
apiVersion: v1
metadata:
  name: cfdrelloweb
  namespace: trainee
spec:
  ports:
  - name: '8080'
    port: 8080
    targetPort: 8080
    nodePort: 30356
  type: NodePort
  selector:
    app: trainee